### PR TITLE
upgrade to bleve v2

### PR DESCRIPTION
**Pull request by mschoch**

### CODE REVIEW

**Comment by TechplexEngineer** [comment]
Any chance of getting a go.mod file with this PR?

`go mod init github.com/blevesearch/bleve-explorer`

or

```
module github.com/blevesearch/bleve-explorer

go 1.15

require (
	github.com/blevesearch/bleve/v2 v2.0.0
	github.com/blevesearch/bleve-mapping-ui v0.4.0
	github.com/elazarl/go-bindata-assetfs v1.0.1
	github.com/gorilla/mux v1.8.0
)
```

**Comment by mschoch** [comment]
@TechplexEngineer yes as I alluded to in the comment in the issue thread, the question is whether or not this should be a v2 of bleve-explorer?  Since it only exists as an example app for bleve, I guess maybe it need not be.  We can just always update it to work with the latest.  Thoughts on this @abhinavdangeti  or @sreekanth-cb

**Comment by TechplexEngineer** [comment]
For what its worth: If making this change breaks using bleve-explorer from go-get then v2 could be appropriate.

**Comment by abhinavdangeti** [comment]
@mschoch To avoid any future build breakages by using the master branch, a go.mod may do some good?

- bleve-mapping-ui@v0.4.0
- bleve@v2.0.1

**Comment by mschoch** [comment]
Haha, not sure why there is so much confusion.  No one is against adding a go.mod, but we have to know what version we're releasing before we do anything.

**Comment by mschoch** [comment]
We have decide to only support bleve-explorer with the current version of bleve, so we are upgrading it to bleve v2 and adding go.mod and go.sum.

**Review by abhinavdangeti — APPROVED** [review]
Looks good to me!

**Pull request merged**
